<a href="https://colab.research.google.com/github/MadhumitaPradhan/DDMDW/blob/main/Ass2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Download a dataset from kaggle and upload it in jupyter notebook or google colab. Perform any random operation on the dataset.¶



In [1]:
import pandas as pd
import numpy as np
from google.colab import files  
uploaded = files.upload()


Saving CarPrice_Assignment.csv to CarPrice_Assignment.csv


In [3]:
import io
df = pd.read_csv(io.BytesIO(uploaded['CarPrice_Assignment.csv']))
df


car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[205 rows x 26 columns]

2) A) Defining three random arrays: a one-dimensional (x1),two-dimensional (x2) and three-dimensional array(x3). Use NumPy’s random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run. B) Display the ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array) of the third array (x3).¶



In [4]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


3) Create two numpy arrays named X and Y of integers using range (1-10) and (11-20) command. Next, create a new array Z by concatenate X and Y.¶



In [5]:
X = np.arange(1,10,dtype = int)
Y = np.arange(11,20,dtype = int)
Z = np.concatenate((X, Y))
print(Z)


[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


4) Define a two-dimensional (X2). Concatenate X2 with X2.¶



In [6]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[11,12,13],[14,15,16]])
Z = np.concatenate((X, Y))
print(Z)


[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


5) A) Create a numpy array named x of integers using range (1-10) command. B) Next, perform x+5, x-5, x/5, x*5, x^2, x%2, log(x),log2(x), log10(x) operations over X. C) Finally, compute some trigonometric functions (sin, cos,tan) on X.¶



In [7]:
X = np.arange(1,10,dtype = int)
print("X+5: ",X+5)
X = np.arange(1,10,dtype = int)
print("X-5: ",X-5)
X = np.arange(1,10,dtype = int)
print("X/5: ",X/5)
X = np.arange(1,10,dtype = int)
print("X*5: ",X*5)
X = np.arange(1,10,dtype = int)
print("X^2: ",np.power(X, 2))
X = np.arange(1,10,dtype = int)
print("X%2: ",np.mod(X,2))
X = np.arange(1,10,dtype = int)
print("log(X): ", np.log(X))
X = np.arange(1,10,dtype = int)
print("log2(X): ", np.log2(X))
X = np.arange(1,10,dtype = int)
print("log10(X): ", np.log10(X))
X = np.arange(1,10,dtype = int)
print("sin: ",np.sin(X))
X = np.arange(1,10,dtype = int)
print("cos: ",np.cos(X))
X = np.arange(1,10,dtype = int)
print("tan: ",np.tan(X))


X+5:  [ 6  7  8  9 10 11 12 13 14]
X-5:  [-4 -3 -2 -1  0  1  2  3  4]
X/5:  [0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
X*5:  [ 5 10 15 20 25 30 35 40 45]
X^2:  [ 1  4  9 16 25 36 49 64 81]
X%2:  [1 0 1 0 1 0 1 0 1]
log(X):  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
log2(X):  [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
log10(X):  [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
tan:  [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]
